#!/bin/bash

cl \
	-e '(load "scripts/generate")' \
	-e '(turtl-gen:generate "chrome/content/data/app/" :index-popup :prepend "app")' \
	-e '(quit)'

chmod 644 chrome/content/data/index.html chrome/content/data/popup/index.html

