#!/bin/bash

pushd chrome/content > /dev/null

cl \
	-e '(load "scripts/generate")' \
	-e '(turtl-gen:generate "data/app/" :index-popup :prepend "app")' \
	-e '(quit)'

chmod 644 data/index.html data/popup/index.html

popd > /dev/null
